### ISSUE TITLE
hdfs-site.xml configuration

### ISSUE THREAD

**Issue by rjudet** [MuhammadBilalYar/Hadoop-On-Window#12]
You might want to set the hdfs in the following way in **hdfs-site.xml**, otherwise might get a  **java.net.URISyntaxException: Illegal character in opaque part at index 2:**

  ```
   <property>
       <name>dfs.namenode.name.dir</name>
       <value>file:///C:/hadoop-2.8.0/data/namenode</value>
   </property>
   <property>
       <name>dfs.datanode.data.dir</name>
       <value>file:///C:/hadoop-2.8.0/data/datanode</value>
   </property>
```
Also, I think the JAVA_HOME and HADOOP_HOME environment variables should be set without the trailing **/bin**.
Otherwise very good step by step instructions. Thanks.

**Comment by MuhammadBilalYar** [comment]
@rjudet are you able to resolve the issue?

**Comment by rjudet** [comment]
@MuhammadBilalYar yes, I was - as explained above. @carlvice To be more clear:
- JAVA_HOME env variable should **NOT** be set with a trailing /bin. In other words, if your installation is at C:\Program Files\Java\jdk1.8.0_xxx, THIS is what you set as JAVA_HOME, NOT C:\Program Files\Java\jdk1.8.0_25\bin. Same is available for HADOOP_HOME. 
Indeed, you will want to **add to your CLASSPATH** JAVA_HOME\bin, and similarly HADOOP_HOME\bin
- Yes, you can eventually get all components up and running. Did you try **to use** them though? I mean to even run an example word count Map Reduce program? That's when you might run into the **java.net.URISyntaxException: Illegal character in opaque part at index 2**. And if you do, you can get around it as I explained above.

Cheers

**Comment by MuhammadBilalYar** [comment]
Sounds good!
