### ISSUE TITLE
Can the same configuration used for windows 7

### ISSUE THREAD

**Issue by soundarpandiyan** [MuhammadBilalYar/Hadoop-On-Window#16]
First of all thanks for the details on installing Hadoop in windows 10. I would like install the same in the windows 7 environment. Also it would be great if you provide any example to run once installation successfully completed

**Comment by soundarpandiyan** [comment]
Noticed that you have already provided example. whether sample steps will work for windows 7. thanks in advance

**Comment by soundarpandiyan** [comment]
It would be great if you explain the multi node cluster installation in windows

**Comment by MuhammadBilalYar** [comment]
you can give a try i will work on window 7 as well.
