### ISSUE TITLE
Command ( hdfs namenode –format ) is not working 

### ISSUE THREAD

**Issue by devayan851989** [MuhammadBilalYar/Hadoop-On-Window#17]
Command ( hdfs namenode –format ) is not working.

**Error message:**

C:\Spark\hadoop\New folder\hadoop-2.8.0.tar\hadoop-2.8.0\hadoop-2.8.0\bin>hdfs namenode -format
'C:\Spark\hadoop\New' is not recognized as an internal or external command,
operable program or batch file.
'-classpath' is not recognized as an internal or external command,
operable program or batch file.

Could you please help me in troubleshooting this issue

**Comment by devayan851989** [comment]
Issue resolved by using points.

1.Space issue in the JDK path causing this issue
Workaround to ignore space ( PROGRA~1 ) in the folder
C:\PROGRA~1\Java\jdk1.8.0_152

2.C drive is not recognized
workaround:Remove C:/ from file ( hdfs-site.xml )
/hadoop-2.8.0/data/namenode

**Comment by MuhammadBilalYar** [comment]
Thanks @devayan851989 ! Also in main artical.

**Comment by eh329** [comment]
@devayan851989 I do not understand how you solved the issue number 1. 
This is my JDK path: C:\Program Files\Java\jdk1.8.0_351 that i saved in hadoop-env.cmd file.
How should i modify this? I would appreciate it, if you answered this. Thanks

**Comment by Sowmya344** [comment]
hello. I cant seem to figure out my error:
I can run the HDFS command, but I cant seem to run any other commands after hdfs command. 
Example: hdfs namenode -format: my windows cmd says that the internal or external command is not found.
What should I do?
![image](https://github.com/user-attachments/assets/0790dc32-32a5-43b5-9f3a-848fc7a41a7c)
![image](https://github.com/user-attachments/assets/5515d90d-e52c-42d5-85b8-31989749d598)
