### ISSUE TITLE
mapreduce.Job: Running job

### ISSUE THREAD

**Issue by ajayrandhawa** [MuhammadBilalYar/Hadoop-On-Window#9]
Stuck a job 

18/08/07 21:58:40 INFO client.RMProxy: Connecting to ResourceManager at /0.0.0.0:8032
18/08/07 21:58:42 INFO input.FileInputFormat: Total input files to process : 1
18/08/07 21:58:43 INFO mapreduce.JobSubmitter: number of splits:1
18/08/07 21:58:43 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1533659271999_0001
18/08/07 21:58:44 INFO impl.YarnClientImpl: Submitted application application_1533659271999_0001
18/08/07 21:58:44 INFO mapreduce.Job: The url to track the job: http://DESKTOP-HES8I7I:8088/proxy/application_1533659271999_0001/
18/08/07 21:58:44 INFO mapreduce.Job: Running job: job_1533659271999_0001

whats Problem

**Comment by sannnan** [comment]
Have you resolved the issue? I am at same state

**Comment by Vishesh51** [comment]
I am also looking for a solution to the problem

**Comment by sannnan** [comment]
I have faced same issue on Linux and I have resolved it by managing memory and space manually. 
Overridden the mapered.xml configuration which suits according to my PC configuration. 

I will ll let you know the details. Be hold
